### ISSUE TITLE
Resources like PDF files cannot be found.

### ISSUE THREAD

**Issue by bangbh81** [Wiznet/document_framework#14]
Resources cannot be found.
https://doc.wiznet.io/img/products/w5500/w5500_ds_v109e.pdf
->>
![image](https://user-images.githubusercontent.com/11305037/91116021-12f30780-e6a9-11ea-8d43-c656a5c98f10.png)

**Comment by joon874** [comment]
To add more details. After open pdf file, web page shows the blow page.
![image](https://user-images.githubusercontent.com/12506773/99519598-6ab5bc00-29d5-11eb-9995-212a14d99863.png)

And **GO back** button does not work
![image](https://user-images.githubusercontent.com/12506773/99519770-a05aa500-29d5-11eb-9ea4-982e9b282e10.png)

**Comment by joon874** [comment]
@albin-joseph-wiznet  please reply for this issue

**Comment by albin-joseph-wiznet** [comment]
LINK IN MD DOCUMENT NEW FORMAT:-
![image](https://user-images.githubusercontent.com/60734163/100307277-70119880-2fcb-11eb-9696-d107e4611360.png)

LINK IN WEBSITE:-
![image](https://user-images.githubusercontent.com/60734163/100307384-b36c0700-2fcb-11eb-932e-1061bb17cb56.png)

SOLUTION DEMO LINK:-

https://docs.wiznet.io/Product/iMCU/W7500/w7500_ref_schematic
